server:
  port: "8080"
  host: "0.0.0.0"
  frontend_assets_path: "frontend"
  logging:
    level: "info"
    caller_depth:
      backend: 8
      frontend: 8
    format: "json"
    output: "stdout"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
    expose_headers: ["*"]
    max_age: 3600
  database:
    dsn:
      users: "file:/app/data/joustlm.db?cache=shared&mode=rwc"
      analyses: "file:/app/data/joustlm.db?cache=shared&mode=rwc"
  security:
    jwt_secret: "joustlm_jwt_secret_key_2024_change_in_production"
    password_salt: "joustlm_password_salt_2024_change_in_production"
    token_expiry_hours: 24
  llm:
    tokenizer:
      model: "bert-base-uncased"
      config: "tokenizer.json"
      max_length: 4000
      stride: 512
      padding: "max_length"
    summarizer:
      base_url: "https://generativelanguage.googleapis.com/v1beta/models"
      endpoint: "/gemini-2.0-flash:generateContent"
      api_key: ""
      model: "gemini-2.0-flash"
