server:
  port: "8080"
  host: "127.0.0.1"
  frontend_assets_path: ""
  logging:
    level: "info"
    caller_depth:
      backend: 8
      frontend: 8
    format: "json"
    output: "stdout"
  cors:
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowed_headers: ["*"]
    allow_credentials: true
    expose_headers: ["*"]
    max_age: 3600
  database:
    dsn:
      users: "file:joustlm.db?cache=shared&mode=rwc"
      analyses: "file:joustlm.db?cache=shared&mode=rwc"
  security:
    jwt_secret: "joustlm_jwt_secret_key_2024_change_in_production"
    password_salt: "joustlm_password_salt_2024_change_in_production"
    token_expiry_hours: 24
  llm:
    api_key: "your-openai-api-key"
    model: "gpt-3.5-turbo"
